language: node_js
node_js:
    - 0.10
notifications:
    email:
        recipients:
            - ypt-team@yahoo-inc.com
        on_success: change
        on_failure: always
env:
  global:
    - secure: P/e4dltlJyW+i4Tp/XQovQdBpeGlAUghryJX5rP19vsgcF9OCj6H3oR/XqvDKeE0nodMTnTxF+nonDSAVC75q9p5wWGTAJf8xQFT0JEPNyWuvD22LHwh2HpMV6TRRb8L0Icd6+NRYGXTakwX6/Sg6PhzWSQvZfVPWE8jAQBBNFs=
    - secure: TuxjACPdPnjhJKzsvd1dZPmoTa8xOQ3jIcUBIkLBzm9V+I/weNC56LnhAbcTY5FREFxxD19OFzgAGtovR/0uZ4TP/fBPeG72mF9pv1+8l8kdfMDsXT13HZs9BTSDtVxEQE9KaVaRJu4+hQ+tpoq1zGWyFqtW97hiEgwxc9Qvbsw=
addons:
  sauce_connect: true
