language: node_js
node_js:
    - 0.10
script: npm run travis
notifications:
    email:
        recipients:
            - ypt-team@yahoo-inc.com
        on_success: change
        on_failure: always
env:
  global:
    - secure: WbnUp5FGES0fYpvlzB8wayHoA2xbAoyge5O5oMpmqh54O/uDBUVscxMXbC/XaW8G/2YTHKXuMOTK5aMHcv7Vci3sa5Xi23gEEW4dZWRyFapG6D/apeftXLv8bsvnVfdjEGxlBVGgCwf0Y1mhWtdkW+lMjim/u7RMHVXkKdcx/aQ=
    - secure: UhWj7DnqwMl3g69ZGj3kaWwro5FpuDxnsrbiw3N2PDM+7HFzWCJNUOOi/2ibGtRrvXm3pT47ivYv4G3ddU8rvSSRpb8VZk01XoeQ56Gt76JKQtpfyvPbHdCSRX43b6jBm5ySIa285f+kmHZ16aCGk1KW2voDA4w04KU27IFYTI0=
